# Generated by Django 3.0.2 on 2020-01-21 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=127)),
                ('middle_names', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=127)),
                ('gender', models.BooleanField()),
                ('age', models.SmallIntegerField()),
                ('image', models.FileField(upload_to='static/media/users/')),
                ('occupation', models.CharField(max_length=127)),
                ('location', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, website.models.Profile),
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('representative_name', models.CharField(max_length=255)),
                ('age_group', models.CharField(choices=[('CR', 'Crianças'), ('JV', 'Jovens'), ('AD', 'Adultos'), ('ID', 'Idosos')], default='AD', max_length=2)),
                ('organization_types', models.ManyToManyField(to='website.OrganizationType')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, website.models.Profile),
        ),
    ]
