# Generated by Django 3.0.2 on 2020-01-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='last_name',
        ),
    ]
