# Generated by Django 3.0.2 on 2020-01-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200128_1059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationType',
            new_name='OrganisationType',
        ),
        migrations.RenameField(
            model_name='organisationprofile',
            old_name='organization_name',
            new_name='organisation_name',
        ),
        migrations.RenameField(
            model_name='organisationprofile',
            old_name='organization_types',
            new_name='organisation_types',
        ),
    ]
