# Generated by Django 3.0.2 on 2020-01-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200128_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationprofile',
            name='age_group',
            field=models.CharField(blank=True, choices=[('CR', 'Crianças'), ('JV', 'Jovens'), ('AD', 'Adultos'), ('ID', 'Idosos')], default='AD', max_length=2),
        ),
        migrations.AlterField(
            model_name='organisationprofile',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organisationprofile',
            name='organisation_types',
            field=models.ManyToManyField(blank=True, to='website.OrganisationType'),
        ),
        migrations.AlterField(
            model_name='organisationprofile',
            name='representative_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='age',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='gender',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='image',
            field=models.FileField(blank=True, upload_to='static/media/users/'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='middle_names',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
