# Generated by Django 3.0.2 on 2020-01-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200128_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='age',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='gender',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
