# Generated by Django 3.0.2 on 2020-01-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200128_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
