# Generated by Django 3.0.2 on 2020-01-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_organisationprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationprofile',
            name='age_group',
            field=models.CharField(blank=True, choices=[('CR', 'Crianças'), ('JV', 'Jovens'), ('AD', 'Adultos'), ('ID', 'Idosos')], max_length=2),
        ),
    ]
