# Generated by Django 3.0.2 on 2020-02-03 20:34

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_names', models.CharField(blank=True, max_length=255)),
                ('gender', models.BooleanField(blank=True, default=False)),
                ('age', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('image', models.FileField(blank=True, upload_to='static/media/users/')),
                ('occupation', models.CharField(blank=True, max_length=127)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, dashboard.models.Profile),
        ),
        migrations.CreateModel(
            name='OrganisationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(blank=True, max_length=255)),
                ('representative_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('age_range', models.ManyToManyField(blank=True, to='dashboard.AgeRange')),
                ('organisation_type', models.ManyToManyField(blank=True, to='dashboard.OrganisationType')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, dashboard.models.Profile),
        ),
    ]
