# Generated by Django 3.0.5 on 2020-04-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
