# Generated by Django 3.0.2 on 2020-02-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='middle_names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
