# Generated by Django 3.0.2 on 2020-02-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
