# Generated by Django 3.0.2 on 2020-02-03 19:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationprofile',
            name='age_group',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Crianças'), (2, 'Jovens'), (3, 'Adultos'), (4, 'Idosos')], max_length=7),
        ),
        migrations.AddField(
            model_name='organisationprofile',
            name='organisation_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Anti-racismo, Anti-fascismo'), (2, 'Refugiados, imigrantes e minorias étnicas'), (3, 'Solidariedade internacional'), (4, 'Paz e desarmamento'), (5, 'Injustiça social'), (6, 'Igualdade de género e sociedade'), (7, 'Crianças e juventude'), (8, 'Idosos'), (9, 'Pessoas com dificuldades'), (10, 'Proteção do ambiente'), (11, 'Clima e estilo vida sustentável'), (12, 'Arte, cultura e história local'), (13, 'Vida da comunidade')], max_length=29),
        ),
    ]
