# Generated by Django 3.0.2 on 2020-02-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200203_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationprofile',
            name='age_group',
        ),
        migrations.AddField(
            model_name='organisationprofile',
            name='age_range',
            field=models.ManyToManyField(blank=True, to='dashboard.AgeRange'),
        ),
        migrations.RemoveField(
            model_name='organisationprofile',
            name='organisation_type',
        ),
        migrations.AddField(
            model_name='organisationprofile',
            name='organisation_type',
            field=models.ManyToManyField(blank=True, to='dashboard.OrganisationType'),
        ),
    ]
