# Generated by Django 3.0.2 on 2020-03-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.OrganisationProfile'),
        ),
    ]
