# Generated by Django 3.0.2 on 2020-02-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200210_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
