# Generated by Django 3.0.5 on 2020-04-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_volunteerprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
