# Generated by Django 3.0.2 on 2020-02-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200206_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationprofile',
            name='image',
            field=models.FileField(blank=True, upload_to='static/media/organisations'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='image',
            field=models.FileField(blank=True, upload_to='static/media/volunteers/'),
        ),
    ]
