# Generated by Django 3.0.2 on 2020-02-10 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200210_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/volunteers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
        ),
    ]
