# Generated by Django 3.0.4 on 2020-04-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200419_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_range',
            field=models.ManyToManyField(blank=True, to='dashboard.AgeRange'),
        ),
        migrations.AddField(
            model_name='event',
            name='organisation_type',
            field=models.ManyToManyField(blank=True, to='dashboard.OrganisationType'),
        ),
    ]
