# Generated by Django 3.0.4 on 2020-04-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200421_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationtype',
            name='description',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
