# Generated by Django 3.0.2 on 2020-03-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200308_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationtype',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
