# Generated by Django 3.0.2 on 2020-02-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200210_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='phone_number',
            field=models.CharField(blank=True, default=0, max_length=12, null=True),
        ),
    ]
