# Generated by Django 3.0.2 on 2020-03-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_organisationtype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationtype',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
