# Generated by Django 3.0.4 on 2020-04-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_eventfilter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventFilter',
        ),
    ]
