# Generated by Django 3.0.2 on 2020-02-13 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200210_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='organisations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='volunteers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
