# Generated by Django 3.0.2 on 2020-02-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200213_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='middle_names',
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
