# Generated by Django 3.0.2 on 2020-02-15 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200213_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='organisations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
        ),
    ]
